spring:
  thymeleaf:
    cache: false
    enabled: true
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/miaosha?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 2000922...
  redis:
    database: 0
    host: gaosong.site
    port: 6379
    password: 123456
mybatis:
  type-aliases-package: com.imooc.miaosha.domain
  mapper-locations: classpath:com/immoc/miaosha/mapper/*.xml
# 日志设置
logging:
  level:
    root: info
    cn.gs: debug
  file:
    name: log/blog-dev.log